# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PCAReportDescriptionGenerator
                                 A QGIS plugin
 Thi plugin generates a ...
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-11-14
        copyright            : (C) 2022 by Valerio Pinna
        email                : vpinna@pre-contruct.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PCAReportDescriptionGenerator class from file PCAReportDescriptionGenerator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .pca_report_description import PCAReportDescriptionGenerator
    return PCAReportDescriptionGenerator(iface)
